[package]
name = "http-parser"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
http = "0.2.8"

[lib]
path = "src/lib.rs"
